version: 2.1
orbs:
  cloudrun: circleci/gcp-cloud-run@1.0
jobs:
  build_and_deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Auth
          command: |
            echo 'export PATH=~$PATH:~/.local/bin' >> $BASH_ENV
            echo ${GCP_PROJECT_KEY} | base64 --decode --ignore-garbage > $HOME/gcloud-service-key.json
            echo 'export GOOGLE_CLOUD_KEYS=$(cat $HOME/gcloud-service-key.json)' >> $BASH_ENV
      - cloudrun/init
      - cloudrun/build:
          tag: "gcr.io/${GOOGLE_PROJECT_ID}/test-${CIRCLE_SHA1}"
          source: ./sample
      - cloudrun/deploy:
          platform: managed
          image: "gcr.io/${GOOGLE_PROJECT_ID}/test-${CIRCLE_SHA1}"
          service-name: "example-service"
          region: "us-east1"
          unauthenticated: true
      - run:
          name: Test the deployed service
          command: |
            if [ "$(curl -s "$GCP_DEPLOY_ENDPOINT")" != "Hello World!" ]; then
              echo "Result is unexpected"
              exit 1;
            fi
workflows:
  deploy_service:
    jobs:
      - build_and_deploy
