version: 2
jobs:
  deploy:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - run:
          name: Authorize GCloud Command Line Tool
          command: |
            echo $GCP_PROJECT_KEY | base64 --decode | gcloud auth activate-service-account --key-file=-
      - run:
          name: Deploy To Google Cloud Functions
          command: |
            # Variables
            FUNCTION_NAME=circleci_deployment_example
            ENTRYPOINT=main
            GCP_PROJECT=circleci-gcf-deployment
            # Deploy command
            gcloud functions deploy $FUNCTION_NAME \
              --entry-point $ENTRYPOINT \
              --runtime python37 \
              --trigger-http \
              --source ./src/ \
              --project $GOOGLE_PROJECT_ID
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master
